// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pos.Infrastructure.Persistence;

#nullable disable

namespace Pos.Infrastructure.Persistence.Migrations.Postgres
{
    [DbContext(typeof(PosDbContext))]
    partial class PosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("core")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pos.Domain.Inventory.InventoryBalance", b =>
                {
                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("BatchKey")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_key");

                    b.Property<short>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.Property<decimal>("AverageUnitCost")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("average_unit_cost");

                    b.Property<DateTimeOffset>("LastMovementAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_movement_at_utc");

                    b.Property<Guid>("LastMovementId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_movement_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("TotalValue")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("total_value");

                    b.HasKey("LocationId", "ProductId", "BatchKey", "State");

                    b.HasIndex("LocationId", "State")
                        .HasDatabaseName("ix_inventory_balance_location_state");

                    b.HasIndex("ProductId", "LocationId")
                        .HasDatabaseName("ix_inventory_balance_product_location");

                    b.ToTable("inventory_balance", "inventory");
                });

            modelBuilder.Entity("Pos.Domain.Inventory.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date")
                        .HasColumnName("business_date");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("DestinationLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_location_id");

                    b.Property<short?>("DestinationState")
                        .HasColumnType("smallint")
                        .HasColumnName("destination_state");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<short>("LegNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("leg_number");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid>("MovementGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("movement_group_id");

                    b.Property<short>("MovementType")
                        .HasColumnType("smallint")
                        .HasColumnName("movement_type");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("QuantityDelta")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity_delta");

                    b.Property<short?>("ReasonCode")
                        .HasColumnType("smallint")
                        .HasColumnName("reason_code");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_utc");

                    b.Property<Guid?>("ReferenceDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_document_id");

                    b.Property<short>("ReferenceDocumentType")
                        .HasColumnType("smallint")
                        .HasColumnName("reference_document_type");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reference_number");

                    b.Property<Guid?>("ReversesMovementGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_movement_group_id");

                    b.Property<short>("ServerProcessingStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("server_processing_status");

                    b.Property<Guid?>("SourceLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_location_id");

                    b.Property<short?>("SourceState")
                        .HasColumnType("smallint")
                        .HasColumnName("source_state");

                    b.Property<short>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.Property<short>("SyncStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("sync_status");

                    b.Property<decimal>("TotalValueDelta")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("total_value_delta");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("unit_cost");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_inventory_movement_event");

                    b.HasIndex("MovementGroupId")
                        .HasDatabaseName("ix_inventory_movement_group");

                    b.HasIndex("MovementGroupId", "LegNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_inventory_movement_group_leg");

                    b.HasIndex("ProductId", "RecordedAtUtc")
                        .HasDatabaseName("ix_inventory_movement_product_time");

                    b.HasIndex("ReferenceDocumentType", "ReferenceDocumentId")
                        .HasDatabaseName("ix_inventory_movement_reference");

                    b.HasIndex("LocationId", "ProductId", "BatchId", "State", "RecordedAtUtc")
                        .HasDatabaseName("ix_inventory_movement_bucket");

                    b.ToTable("inventory_movement", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_inventory_movement_cost_nonnegative", "unit_cost >= 0");

                            t.HasCheckConstraint("ck_inventory_movement_leg_positive", "leg_number >= 1");

                            t.HasCheckConstraint("ck_inventory_movement_quantity_nonzero", "quantity_delta <> 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
