// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pos.Infrastructure.Offline;

#nullable disable

namespace Pos.Infrastructure.Persistence.Migrations.Sqlite
{
    [DbContext(typeof(PosDeviceDbContext))]
    [Migration("20260917113840_DeviceLocalSale")]
    partial class DeviceLocalSale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Pos.Domain.Inventory.InventoryBalance", b =>
                {
                    b.Property<Guid>("LocationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("location_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.Property<Guid>("BatchKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("batch_key");

                    b.Property<short>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state");

                    b.Property<string>("AverageUnitCost")
                        .IsRequired()
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("average_unit_cost");

                    b.Property<string>("LastMovementAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_movement_at_utc");

                    b.Property<Guid>("LastMovementId")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_movement_id");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity");

                    b.Property<string>("TotalValue")
                        .IsRequired()
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("total_value");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("LocationId", "ProductId", "BatchKey", "State");

                    b.HasIndex("LocationId", "State")
                        .HasDatabaseName("ix_inventory_balance_location_state");

                    b.HasIndex("ProductId", "LocationId")
                        .HasDatabaseName("ix_inventory_balance_product_location");

                    b.ToTable("local_inventory_balance", null, t =>
                        {
                            t.HasTrigger("trg_local_inventory_balance_ledger_only_delete");

                            t.HasTrigger("trg_local_inventory_balance_ledger_only_insert");

                            t.HasTrigger("trg_local_inventory_balance_ledger_only_update");
                        });
                });

            modelBuilder.Entity("Pos.Domain.Inventory.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("approved_by_user_id");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("TEXT")
                        .HasColumnName("batch_id");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("business_date");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("DestinationLocationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("destination_location_id");

                    b.Property<short?>("DestinationState")
                        .HasColumnType("INTEGER")
                        .HasColumnName("destination_state");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("device_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_id");

                    b.Property<short>("LegNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("leg_number");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("location_id");

                    b.Property<Guid>("MovementGroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("movement_group_id");

                    b.Property<short>("MovementType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("movement_type");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("OccurredAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.Property<string>("QuantityDelta")
                        .IsRequired()
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity_delta");

                    b.Property<short?>("ReasonCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reason_code");

                    b.Property<string>("RecordedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at_utc");

                    b.Property<Guid?>("ReferenceDocumentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("reference_document_id");

                    b.Property<short>("ReferenceDocumentType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reference_document_type");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("reference_number");

                    b.Property<Guid?>("ReversesMovementGroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("reverses_movement_group_id");

                    b.Property<short>("ServerProcessingStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("server_processing_status");

                    b.Property<Guid?>("SourceLocationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_location_id");

                    b.Property<short?>("SourceState")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_state");

                    b.Property<short>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state");

                    b.Property<short>("SyncStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sync_status");

                    b.Property<string>("TotalValueDelta")
                        .IsRequired()
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("total_value_delta");

                    b.Property<string>("UnitCost")
                        .IsRequired()
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_cost");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_inventory_movement_event");

                    b.HasIndex("MovementGroupId")
                        .HasDatabaseName("ix_inventory_movement_group");

                    b.HasIndex("MovementGroupId", "LegNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_inventory_movement_group_leg");

                    b.HasIndex("ProductId", "RecordedAtUtc")
                        .HasDatabaseName("ix_inventory_movement_product_time");

                    b.HasIndex("ReferenceDocumentType", "ReferenceDocumentId")
                        .HasDatabaseName("ix_inventory_movement_reference");

                    b.HasIndex("LocationId", "ProductId", "BatchId", "State", "RecordedAtUtc")
                        .HasDatabaseName("ix_inventory_movement_bucket");

                    b.ToTable("local_inventory_movement", null, t =>
                        {
                            t.HasTrigger("trg_local_inventory_movement_immutable_delete");

                            t.HasTrigger("trg_local_inventory_movement_immutable_update");

                            t.HasCheckConstraint("ck_inventory_movement_cost_nonnegative", "unit_cost >= 0");

                            t.HasCheckConstraint("ck_inventory_movement_leg_positive", "leg_number >= 1");

                            t.HasCheckConstraint("ck_inventory_movement_quantity_nonzero", "quantity_delta <> 0");
                        });
                });

            modelBuilder.Entity("Pos.Domain.Sales.CashierShift", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("business_date");

                    b.Property<string>("CashVariance")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("cash_variance");

                    b.Property<Guid>("CashierUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("cashier_user_id");

                    b.Property<string>("ClosedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("closed_at_utc");

                    b.Property<string>("CountedCash")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("counted_cash");

                    b.Property<string>("DeclaredCash")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("declared_cash");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("device_id");

                    b.Property<bool>("IsForceClosed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_force_closed");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("location_id");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("number");

                    b.Property<string>("OpenedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("opened_at_utc");

                    b.Property<string>("OpeningFloat")
                        .IsRequired()
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("opening_float");

                    b.Property<short>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ux_local_cashier_shift_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_local_cashier_shift_status");

                    b.ToTable("local_cashier_shift", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Sales.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeactivatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeactivationReason")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tin")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Pos.Domain.Sales.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("amount");

                    b.Property<string>("Change")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("change_given");

                    b.Property<short>("Method")
                        .HasColumnType("INTEGER")
                        .HasColumnName("method");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_reference");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("sale_id");

                    b.Property<string>("Tendered")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("tendered");

                    b.HasKey("Id");

                    b.HasIndex("SaleId", "Id")
                        .HasDatabaseName("ix_payment_sale");

                    b.ToTable("local_payment", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Sales.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("business_date");

                    b.Property<Guid>("CashierShiftId")
                        .HasColumnType("TEXT")
                        .HasColumnName("cashier_shift_id");

                    b.Property<string>("CompletedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at_utc");

                    b.Property<Guid>("CompletedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_by_user_id");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("device_id");

                    b.Property<string>("DiscountTotal")
                        .IsRequired()
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("discount_total");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_id");

                    b.Property<string>("GrossTotal")
                        .IsRequired()
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("gross_total");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("location_id");

                    b.Property<string>("NetTotal")
                        .IsRequired()
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("net_total");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("number");

                    b.Property<short>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("TaxableBaseTotal")
                        .IsRequired()
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("taxable_base_total");

                    b.Property<string>("VatExemptTotal")
                        .IsRequired()
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("vat_exempt_total");

                    b.Property<string>("VatTotal")
                        .IsRequired()
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("vat_total");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("void_reason");

                    b.Property<string>("VoidedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("voided_at_utc");

                    b.Property<Guid?>("VoidedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("voided_by_user_id");

                    b.Property<string>("ZeroRatedTotal")
                        .IsRequired()
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("zero_rated_total");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ux_sale_event_id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ux_sale_number");

                    b.HasIndex("CashierShiftId", "Id")
                        .HasDatabaseName("ix_sale_shift");

                    b.HasIndex("LocationId", "BusinessDate")
                        .HasDatabaseName("ix_sale_location_business_date");

                    b.ToTable("local_sale", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Sales.SaleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT")
                        .HasColumnName("barcode");

                    b.Property<string>("BatchCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("batch_code");

                    b.Property<DateOnly?>("BatchExpiresOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("batch_expires_on");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("TEXT")
                        .HasColumnName("batch_id");

                    b.Property<string>("Discount")
                        .IsRequired()
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("discount_amount");

                    b.Property<Guid?>("DiscountAuthorizedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("discount_authorized_by_user_id");

                    b.Property<string>("GrossAmount")
                        .IsRequired()
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("gross_amount");

                    b.Property<bool>("IsVatExempt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_vat_exempt");

                    b.Property<bool>("IsZeroRated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_zero_rated");

                    b.Property<int>("LineNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("line_no");

                    b.Property<string>("NetAmount")
                        .IsRequired()
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("net_amount");

                    b.Property<Guid?>("PriceOverrideAuthorizedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("price_override_authorized_by_user_id");

                    b.Property<Guid>("PriceVersion")
                        .HasColumnType("TEXT")
                        .HasColumnName("price_version");

                    b.Property<bool>("PriceWasOverridden")
                        .HasColumnType("INTEGER")
                        .HasColumnName("price_was_overridden");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("product_name");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity");

                    b.Property<string>("ReturnedQuantity")
                        .IsRequired()
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("returned_quantity");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("sale_id");

                    b.Property<string>("UnitCost")
                        .IsRequired()
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_cost");

                    b.Property<Guid>("UnitOfMeasureId")
                        .HasColumnType("TEXT")
                        .HasColumnName("uom_id");

                    b.Property<string>("UnitPrice")
                        .IsRequired()
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_price");

                    b.Property<string>("Vat")
                        .IsRequired()
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("vat_amount");

                    b.Property<string>("VatBase")
                        .IsRequired()
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("vat_base");

                    b.Property<string>("VatRate")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("vat_rate");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "SaleId")
                        .HasDatabaseName("ix_sale_item_product");

                    b.HasIndex("SaleId", "LineNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_sale_item_line_no");

                    b.ToTable("local_sale_item", (string)null);
                });

            modelBuilder.Entity("Pos.Infrastructure.Offline.DeviceCachedBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ExpiresOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_on");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("lot_number");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.Property<DateOnly>("ReceivedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("received_on");

                    b.Property<string>("UnitCost")
                        .IsRequired()
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_cost");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "ExpiresOn")
                        .HasDatabaseName("ix_cache_batch_fefo");

                    b.ToTable("cache_batch", null, t =>
                        {
                            t.HasTrigger("trg_cache_batch_feed_only_delete");

                            t.HasTrigger("trg_cache_batch_feed_only_insert");

                            t.HasTrigger("trg_cache_batch_feed_only_update");
                        });
                });

            modelBuilder.Entity("Pos.Infrastructure.Offline.DeviceCachedLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<short>("Kind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SettingsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("settings_json");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_cache_location_code");

                    b.ToTable("cache_location", null, t =>
                        {
                            t.HasTrigger("trg_cache_location_feed_only_delete");

                            t.HasTrigger("trg_cache_location_feed_only_insert");

                            t.HasTrigger("trg_cache_location_feed_only_update");
                        });
                });

            modelBuilder.Entity("Pos.Infrastructure.Offline.DeviceCachedProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsVatExempt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_vat_exempt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("sku");

                    b.Property<long>("SourceVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_version");

                    b.Property<bool>("TracksBatches")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tracks_batches");

                    b.Property<bool>("TracksExpiry")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tracks_expiry");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ux_cache_product_sku");

                    b.ToTable("cache_product", null, t =>
                        {
                            t.HasTrigger("trg_cache_product_feed_only_delete");

                            t.HasTrigger("trg_cache_product_feed_only_insert");

                            t.HasTrigger("trg_cache_product_feed_only_update");
                        });
                });

            modelBuilder.Entity("Pos.Infrastructure.Offline.DeviceCachedProductBarcode", b =>
                {
                    b.Property<string>("Barcode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("barcode");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.HasKey("Barcode");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_cache_product_barcode_product");

                    b.ToTable("cache_product_barcode", null, t =>
                        {
                            t.HasTrigger("trg_cache_product_barcode_feed_only_delete");

                            t.HasTrigger("trg_cache_product_barcode_feed_only_insert");

                            t.HasTrigger("trg_cache_product_barcode_feed_only_update");
                        });
                });

            modelBuilder.Entity("Pos.Infrastructure.Offline.DeviceCachedProductPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<string>("EffectiveFromUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("effective_from_utc");

                    b.Property<string>("EffectiveToUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("effective_to_utc");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("location_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "LocationId", "EffectiveFromUtc")
                        .HasDatabaseName("ix_cache_product_price_effective");

                    b.ToTable("cache_product_price", null, t =>
                        {
                            t.HasTrigger("trg_cache_product_price_feed_only_delete");

                            t.HasTrigger("trg_cache_product_price_feed_only_insert");

                            t.HasTrigger("trg_cache_product_price_feed_only_update");
                        });
                });

            modelBuilder.Entity("Pos.Infrastructure.Offline.DeviceCachedUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<long>("SecurityVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("security_version");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("ux_cache_user_name");

                    b.ToTable("cache_user", null, t =>
                        {
                            t.HasTrigger("trg_cache_user_feed_only_delete");

                            t.HasTrigger("trg_cache_user_feed_only_insert");

                            t.HasTrigger("trg_cache_user_feed_only_update");
                        });
                });

            modelBuilder.Entity("Pos.Infrastructure.Offline.DeviceDocumentCounter", b =>
                {
                    b.Property<short>("DocumentType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("document_type");

                    b.Property<string>("PeriodKey")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("period_key");

                    b.Property<long>("NextValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("next_value");

                    b.HasKey("DocumentType", "PeriodKey");

                    b.ToTable("document_counter", (string)null);
                });

            modelBuilder.Entity("Pos.Infrastructure.Offline.DeviceLocalAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("device_id");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_type");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("location_id");

                    b.Property<string>("NewValueJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("new_value_json");

                    b.Property<string>("PreviousValueJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("previous_value_json");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("RecordedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at_utc");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAtUtc")
                        .HasDatabaseName("ix_local_audit_recorded");

                    b.ToTable("local_audit", (string)null);
                });

            modelBuilder.Entity("Pos.Infrastructure.Offline.DevicePermissionSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ExpiresAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("IssuedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("issued_at_utc");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("location_id");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("permission");

                    b.Property<long>("PolicyVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("policy_version");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_snapshot_permission_expiry");

                    b.HasIndex("UserId", "Permission")
                        .IsUnique()
                        .HasDatabaseName("ux_snapshot_permission_global")
                        .HasFilter("location_id IS NULL");

                    b.HasIndex("UserId", "Permission", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("ux_snapshot_permission_location")
                        .HasFilter("location_id IS NOT NULL");

                    b.ToTable("snapshot_permission", null, t =>
                        {
                            t.HasTrigger("trg_snapshot_permission_feed_only_delete");

                            t.HasTrigger("trg_snapshot_permission_feed_only_insert");

                            t.HasTrigger("trg_snapshot_permission_feed_only_update");
                        });
                });

            modelBuilder.Entity("Pos.Infrastructure.Offline.DeviceSequence", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("NextValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("next_value");

                    b.HasKey("Name");

                    b.ToTable("device_sequence", (string)null);
                });

            modelBuilder.Entity("Pos.Infrastructure.Offline.DeviceStoreProfile", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("device_id");

                    b.Property<string>("EnrolledAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("enrolled_at_utc");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("location_id");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT")
                        .HasColumnName("short_code");

                    b.HasKey("DeviceId");

                    b.HasIndex("ShortCode")
                        .IsUnique()
                        .HasDatabaseName("ux_device_profile_short_code");

                    b.ToTable("device_profile", (string)null);
                });

            modelBuilder.Entity("Pos.Infrastructure.Offline.DeviceSyncCursor", b =>
                {
                    b.Property<string>("Feed")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("feed");

                    b.Property<string>("AdvancedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("advanced_at_utc");

                    b.Property<long>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position");

                    b.HasKey("Feed");

                    b.ToTable("sync_cursor", null, t =>
                        {
                            t.HasTrigger("trg_sync_cursor_feed_only_delete");

                            t.HasTrigger("trg_sync_cursor_feed_only_insert");

                            t.HasTrigger("trg_sync_cursor_feed_only_update");
                        });
                });

            modelBuilder.Entity("Pos.Infrastructure.Offline.OutboxEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt_count");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("device_id");

                    b.Property<long>("DeviceSequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("device_sequence");

                    b.Property<long>("DeviceUptimeTicks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("device_uptime_ticks");

                    b.Property<string>("LastAttemptAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_attempt_at_utc");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("location_id");

                    b.Property<string>("NextRetryAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_retry_at_utc");

                    b.Property<string>("OccurredAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at_utc");

                    b.Property<byte[]>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("payload_hash");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(64000)
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_json");

                    b.Property<string>("ServerResponseJson")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT")
                        .HasColumnName("server_response_json");

                    b.Property<short>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<short>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("EventId");

                    b.HasIndex("DeviceSequence")
                        .IsUnique()
                        .HasDatabaseName("ux_local_outbox_sequence");

                    b.HasIndex("Status", "DeviceSequence")
                        .HasDatabaseName("ix_local_outbox_status_sequence");

                    b.ToTable("local_outbox_event", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Sales.Payment", b =>
                {
                    b.HasOne("Pos.Domain.Sales.Sale", null)
                        .WithMany("Payments")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Sales.Sale", b =>
                {
                    b.HasOne("Pos.Domain.Sales.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Pos.Domain.Sales.SaleItem", b =>
                {
                    b.HasOne("Pos.Domain.Sales.Sale", null)
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Sales.Sale", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
