// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pos.Infrastructure.Offline;

#nullable disable

namespace Pos.Infrastructure.Persistence.Migrations.Sqlite
{
    [DbContext(typeof(PosDeviceDbContext))]
    [Migration("20260917083850_DeviceDocumentCounter")]
    partial class DeviceDocumentCounter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Pos.Infrastructure.Offline.DeviceCachedLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<short>("Kind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_cache_location_code");

                    b.ToTable("cache_location", null, t =>
                        {
                            t.HasTrigger("trg_cache_location_feed_only_delete");

                            t.HasTrigger("trg_cache_location_feed_only_insert");

                            t.HasTrigger("trg_cache_location_feed_only_update");
                        });
                });

            modelBuilder.Entity("Pos.Infrastructure.Offline.DeviceCachedProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("sku");

                    b.Property<long>("SourceVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_version");

                    b.Property<bool>("TracksBatches")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tracks_batches");

                    b.Property<bool>("TracksExpiry")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tracks_expiry");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ux_cache_product_sku");

                    b.ToTable("cache_product", null, t =>
                        {
                            t.HasTrigger("trg_cache_product_feed_only_delete");

                            t.HasTrigger("trg_cache_product_feed_only_insert");

                            t.HasTrigger("trg_cache_product_feed_only_update");
                        });
                });

            modelBuilder.Entity("Pos.Infrastructure.Offline.DeviceCachedProductBarcode", b =>
                {
                    b.Property<string>("Barcode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("barcode");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.HasKey("Barcode");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_cache_product_barcode_product");

                    b.ToTable("cache_product_barcode", null, t =>
                        {
                            t.HasTrigger("trg_cache_product_barcode_feed_only_delete");

                            t.HasTrigger("trg_cache_product_barcode_feed_only_insert");

                            t.HasTrigger("trg_cache_product_barcode_feed_only_update");
                        });
                });

            modelBuilder.Entity("Pos.Infrastructure.Offline.DeviceCachedProductPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<string>("EffectiveFromUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("effective_from_utc");

                    b.Property<string>("EffectiveToUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("effective_to_utc");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("location_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "LocationId", "EffectiveFromUtc")
                        .HasDatabaseName("ix_cache_product_price_effective");

                    b.ToTable("cache_product_price", null, t =>
                        {
                            t.HasTrigger("trg_cache_product_price_feed_only_delete");

                            t.HasTrigger("trg_cache_product_price_feed_only_insert");

                            t.HasTrigger("trg_cache_product_price_feed_only_update");
                        });
                });

            modelBuilder.Entity("Pos.Infrastructure.Offline.DeviceCachedUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<long>("SecurityVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("security_version");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("ux_cache_user_name");

                    b.ToTable("cache_user", null, t =>
                        {
                            t.HasTrigger("trg_cache_user_feed_only_delete");

                            t.HasTrigger("trg_cache_user_feed_only_insert");

                            t.HasTrigger("trg_cache_user_feed_only_update");
                        });
                });

            modelBuilder.Entity("Pos.Infrastructure.Offline.DeviceDocumentCounter", b =>
                {
                    b.Property<short>("DocumentType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("document_type");

                    b.Property<string>("PeriodKey")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("period_key");

                    b.Property<long>("NextValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("next_value");

                    b.HasKey("DocumentType", "PeriodKey");

                    b.ToTable("document_counter", (string)null);
                });

            modelBuilder.Entity("Pos.Infrastructure.Offline.DevicePermissionSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ExpiresAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("IssuedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("issued_at_utc");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("location_id");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("permission");

                    b.Property<long>("PolicyVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("policy_version");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_snapshot_permission_expiry");

                    b.HasIndex("UserId", "Permission")
                        .IsUnique()
                        .HasDatabaseName("ux_snapshot_permission_global")
                        .HasFilter("location_id IS NULL");

                    b.HasIndex("UserId", "Permission", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("ux_snapshot_permission_location")
                        .HasFilter("location_id IS NOT NULL");

                    b.ToTable("snapshot_permission", null, t =>
                        {
                            t.HasTrigger("trg_snapshot_permission_feed_only_delete");

                            t.HasTrigger("trg_snapshot_permission_feed_only_insert");

                            t.HasTrigger("trg_snapshot_permission_feed_only_update");
                        });
                });

            modelBuilder.Entity("Pos.Infrastructure.Offline.DeviceStoreProfile", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("device_id");

                    b.Property<string>("EnrolledAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("enrolled_at_utc");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("location_id");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT")
                        .HasColumnName("short_code");

                    b.HasKey("DeviceId");

                    b.HasIndex("ShortCode")
                        .IsUnique()
                        .HasDatabaseName("ux_device_profile_short_code");

                    b.ToTable("device_profile", (string)null);
                });

            modelBuilder.Entity("Pos.Infrastructure.Offline.DeviceSyncCursor", b =>
                {
                    b.Property<string>("Feed")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("feed");

                    b.Property<string>("AdvancedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("advanced_at_utc");

                    b.Property<long>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position");

                    b.HasKey("Feed");

                    b.ToTable("sync_cursor", null, t =>
                        {
                            t.HasTrigger("trg_sync_cursor_feed_only_delete");

                            t.HasTrigger("trg_sync_cursor_feed_only_insert");

                            t.HasTrigger("trg_sync_cursor_feed_only_update");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
